### ISSUE TITLE
Feature Request: Element access using element names

### ISSUE THREAD

**Issue by Jerreeee** [fdlombae/FlyFish#4]
The ability to write data[e0] instead of data[0] would be super handy. And this for all the elements. Mentally keeping track of what elements have which index takes a lot of effort and time to reason about operations.

**Comment by fdlombae** [comment]
Added the requested feature, had to look for some workarounds to allow this syntax in cpp, but got it working with a proxy class.
This however doubles the necessary memory for each object, so I went for a simple inline accessor function. Not perfect, but might come in handy!

**Comment by Jerreeee** [comment]
Appreciate it! This comes in handy.
